version: '3.7'

services:
  pgadmin:
    container_name: ${COMPOSE_PROJECT_NAME}_${SERVICE_NAME}
    build:
      context: ./
      args:
        - DOCKER_IMAGE
        - APP_PREFIX
        - PGADMIN_USER_DIR
        - POSTGRES_HOST_NAME
        - POSTGRES_PORT
        - POSTGRES_DEFAULT_DATABASE_NAME
        - POSTGRES_SUPER_USER_ROLE_NAME
        - POSTGRES_SUPER_USER_SECRET
    restart: ${DOCKER_RESTART_POLICY}   
    env_file:
      - ${DOCKER_GENERATED_ENV_FILE:-./env/defaults}     
    ports:
      - ${PGADMIN_HTTP_PORT}
    volumes:
      - data:/var/lib/pgadmin      
    networks:
      backend:
        aliases: 
          - ${SERVICE_NAME}
      frontend:
        aliases: 
          - ${SERVICE_NAME} 
    logging:
      driver: ${DOCKER_LOGGING_DRIVER}
      options:
        max-file: ${DOCKER_LOGGING_MAX_FILE}
        max-size: ${DOCKER_LOGGING_MAX_SIZE}      
    labels:
      - traefik.http.routers.${APP_PREFIX}-${SERVICE_NAME}-host.rule=Host(`${SERVICE_NAME}.${APP_PREFIX}.${PROXY_ROUTER_DOMAIN}`)
      - traefik.http.routers.${APP_PREFIX}-${SERVICE_NAME}-path.rule=PathPrefix(`/${APP_PREFIX}/${SERVICE_NAME}`)
      
      - traefik.http.services.${APP_PREFIX}-${SERVICE_NAME}.loadbalancer.server.port=${PGADMIN_HTTP_PORT}

      - traefik.http.middlewares.${APP_PREFIX}-${SERVICE_NAME}-stripprefix.stripprefix.prefixes=/${APP_PREFIX}/${SERVICE_NAME}

      - traefik.http.middlewares.${APP_PREFIX}-${SERVICE_NAME}-middlewares-path.chain.middlewares=${APP_PREFIX}-${SERVICE_NAME}-stripprefix
      - traefik.http.routers.${APP_PREFIX}-${SERVICE_NAME}-path.middlewares=${APP_PREFIX}-${SERVICE_NAME}-middlewares-path

networks:
  backend:
    name: ${APP_PREFIX}_${DOCKER_BACKEND_NETWORK_NAME}
  frontend:
    name: ${DOCKER_FRONTEND_NETWORK_NAME}

volumes:
  data:
    name: ${PGADMIN_VOLUME_NAME}
    driver: local      