version: '3.7'

services:
  pgadmin:
    image: ${DOCKER_IMAGE}
    restart: ${DOCKER_RESTART_POLICY}   
    env_file:
      - ${DOCKER_GENERATED_ENV_FILE:-./env/defaults}     
    ports:
      - ${PGADMIN_HTTP_PORT}
    volumes:
      - data:/var/lib/pgadmin      
    networks:
      - backend
      - frontend
    logging:
      driver: ${DOCKER_LOGGING_DRIVER}
      options:
        max-file: ${DOCKER_LOGGING_MAX_FILE}
        max-size: ${DOCKER_LOGGING_MAX_SIZE}      
    labels:
      - pgadmin.http.routers.${APP_PREFIX}-${SERVICE_NAME}-host.rule=Host(`${SERVICE_NAME}.${APP_PREFIX}.localhost`)
      - pgadmin.http.routers.${APP_PREFIX}-${SERVICE_NAME}-path.rule=Host(`${APP_PREFIX}.localhost`) && PathPrefix(`/${SERVICE_NAME}`)
      - pgadmin.http.services.${APP_PREFIX}-${SERVICE_NAME}.loadbalancer.server.port=${PGADMIN_HTTP_PORT}

networks:
  backend:
    name: ${APP_PREFIX}_${DOCKER_BACKEND_NETWORK_NAME}
  frontend:
    name: ${DOCKER_FRONTEND_NETWORK_NAME}

volumes:
  data:
    name: ${PGADMIN_VOLUME_NAME}
    driver: local      